COMPANY_TERMS = {
    "TSM": ["taiwan semiconductor", "tsmc"],
    "NVDA": ["nvidia"],
    "MSFT": ["microsoft"],
    "NBIS": ["nebius"],
    "MU": ["micron"],
    "GOOGL": ["alphabet", "google"],
    "SNDK": ["sandisk"],
    "AVGO": ["broadcom", "vmware"],
    "AMD": ["advanced micro devices", "amd"],
    "ASML": ["asml"],
    "AMZN": ["amazon", "aws", "amazon web services"],
    "SDGR": ["schrodinger", "schrödinger"],
    "RXRX": ["recursion pharmaceuticals", "recursion"],
    "ABSI": ["absci"],
}

SECTOR_TERMS = {
    "TSM": ["semiconductor", "foundry", "ai chip", "chip production", "wafer", "advanced packaging"],
    "NVDA": ["gpu", "ai chip", "semiconductor", "data center", "accelerator", "cuda"],
    "MSFT": ["azure", "copilot", "openai", "cloud", "ai chip", "enterprise ai"],
    "NBIS": ["ai cloud", "gpu cloud", "data center", "ai infrastructure"],
    "MU": ["memory chip", "dram", "hbm", "nand", "semiconductor", "memory"],
    "GOOGL": ["search advertising", "google cloud", "gemini", "artificial intelligence", "ai model"],
    "SNDK": ["flash memory", "nand", "data storage", "memory chip", "semiconductor"],
    "AVGO": ["ai chip", "custom accelerator", "networking chip", "semiconductor", "data center", "vmware"],
    "AMD": ["gpu", "cpu", "ai accelerator", "semiconductor", "data center", "instinct"],
    "ASML": ["lithography", "euv", "semiconductor equipment", "chipmaking equipment", "high-na"],
    "AMZN": ["aws", "amazon web services", "cloud", "bedrock", "trainium", "artificial intelligence"],
    "SDGR": ["ai drug discovery", "computational chemistry", "molecular simulation", "drug discovery platform", "biotech"],
    "RXRX": ["ai drug discovery", "techbio", "drug discovery platform", "phenomics", "biotech"],
    "ABSI": ["generative ai", "drug creation", "biologics", "protein design", "ai drug discovery", "biotech"],
}
